package com.Danthedev.Tradebot;

public enum UserState {
    WAITING_FOR_CRYPTO_SYMBOL_FULL_RESPONSE, WAITING_FOR_CRYPTO_SYMBOL_SIMPLE_RESPONSE, WAITING_FOR_CRYPTO_SEARCH_SYMBOL,
    WAITING_FOR_STOCK_SYMBOL, WAITING_FOR_STOCK_SEARCH_SYMBOL, WAITING_FOR_CREATE_ALERT_SYMBOL, WAITING_FOR_CREATE_ALERT_PRICE,
    WAITING_FOR_DELETE_ALERT_SYMBOL,WAITING_FOR_FROM_CURRENCY, WAITING_FOR_TO_CURRENCY
}
